language: php
php:
    - 5.6
    - 7.0
    - hhvm
before_script:
    - curl -s http://getcomposer.org/installer | php
    - composer install --prefer-source --no-interaction --dev
script:
    - phpunit --configuration phpunit.xml.dist
notifications:
    on_success: never
    on_failure: always