language: php
php:
    - 5.6
    - 7.0
    - hhvm
before_script:
    - sudo apt-get -y remove libcurl4-gnutls-dev
    - sudo apt-get -y install libcurl4-openssl-dev
    - sudo apt-get -y update
    - composer self-update
    - curl -s http://getcomposer.org/installer | php
    - composer install --prefer-source --no-interaction --dev
script:
    - phpunit --configuration phpunit.xml.dist
notifications:
    on_success: never
    on_failure: always